### ISSUE TITLE
Internet Access

### ISSUE THREAD

**Issue by Quantum-Future** [jenspfahl/BDT#10]
Hello, why this app needs "Full Network Access" permission?  (according to F-Droid)

**Comment by jenspfahl** [comment]
The app doesn't need internet access as you can see here (https://github.com/jenspfahl/BDT/blob/master/android/app/src/main/AndroidManifest.xml). I assume a Flutter plugin i import adds this to the merged apk. I'll remove this permission from the built apk permanently with the next release.

**Comment by Quantum-Future** [comment]
Great !
It shocked me when I saw this permission on F-Droid.

**Comment by jenspfahl** [comment]
Fixed with V1.2.1
