### ISSUE TITLE
Some UX suggestions

### ISSUE THREAD

**Issue by offset-torque** [jenspfahl/BDT#2]
Firstly congratulations for the innovative and clever UI.
Your app has the easiest interval setting method I have ever used.
Since it looks promising I decided to write down some suggestions to improve the user experience.
Of course decision to apply them is up to you.
I ordered them from most important to the least.

**1. Vibration can't be disabled**
Even if I set Vibrate to **OFF** in the Settings menu, app still vibrates during start and breaks.
I think this is a bug. If not, there should be a setting to turn off the vibration completely.

**2. App should remember the last settings**
This one is really important. App should remember the settings when it exits.
Because users will probably want use the same duration and intervals next time.

If I am studying for 45 minutes each session, I don't want to set the duration every time I open the app.
Don't make me do this over and over again when you can just remember it:
**1 tap --> 1 scroll --> ~5 scroll --> 1 tap**

Yes there is a pin for interval but without a "duration pin" it is not that useful.
I would say it is even less useful than the duration because interval is highly variable.
User might want to study for 30 minutes (1/2), rest his eyes every 20 minutes (1/3), check the soup every 5 minutes (1/4) etc.

So in short, remember user's last duration/interval and show that next time.
It will benefit users who will use the same settings.
It won't change anything for the rest.

**3. Ability to repeat the timer**
Users might want to repeat the timer after the completion (study, exercise, reading timer etc.).
So you can provide an option for this. Basically "Repeat this cycle until I press STOP or exit the app".

**4. Notify breaks via camera flash**
Some interval timer apps have this option. I think it is very useful because it allows user to be notified without making noise. Because vibration makes noise too, and can be very loud depending on the model of the phone.
So if it is possible, adding this feature would allow the app to be used at night while studying with someone sleeping in the same room for example.

**5. Interval bar location**
This one is less important but may improve usability.
You may want to move interval selection bar under the circle, over the "START" button.
If you do this, user can "set duration > set interval > start" with his thumb while holding the phone in one hand.
Current interval bar is too high and requires stretching up. And in newer phones with long screens it might be really hard to reach.

**Comment by jenspfahl** [comment]
Hey and thank you for all these suggestions and feedback, i appreciate that!
1. I just tried it and it seems that the vibration comes from the app-notification. I think the app should send notifications without vibration option when vibration is disabled. I will try to check that out and align it.

**Comment by jenspfahl** [comment]
2. I see the point.  I was also thinking about saving the selected duration together with the intervals/breaks.

**Comment by jenspfahl** [comment]
3.  I have never thought about that, but it could be useful for repetitive activities, true. I will put it into my agenda.

**Comment by jenspfahl** [comment]
4. Cool idea! Don't know how to achieve this yet but definitely a cool feature!

**Comment by jenspfahl** [comment]
5. I like the current design with the bar on top. But i understand your need. I could imagine an option to make the bar appear underneath the circle.

**Comment by offset-torque** [comment]
Thanks for open minded replies. I don't know if you are aware but if you fix number 1 and implement 2-3, your app will be better than 90% of meditation apps and breathing apps in the android ecosystem. Because they are basically interval timers with a bad UI to set intervals and their intervals are rigid so you need to make many interval sets for different length of meditations. Your one click interval setting and auto calculation is unique and very easy. After implementing these, I suggest posting about your app in **Android** and **Meditation** subreddits to reach more people. I stumbled upon your app accidentally and it deserves more users and I think they will appreciate it too.

Regarding number 5, I don't have a problem with the bar position since my phone is relatively sane sized :) I just wanted to point out that with giant 21:9 phones nowadays it might be too high. Not very important but you can keep this in mind if you think of a redesign someday or if someone complains about it.

**Comment by jenspfahl** [comment]
Regarding 1: As workaround you can disable  vibration for notifications initiated by Break.Down.Timer in the Android settings.
