### ISSUE TITLE
Allow zero breaks

### ISSUE THREAD

**Issue by Insti** [jenspfahl/BDT#5]
I would like to be able to run a timer with zero breaks.

Currently if you try to start a timer with zero breaks placed you get an error message and the timer does not start.

This will allow me to also use this app in the case where I don't want to be notified during a task.

**Comment by Insti** [comment]
A workaround I found was to add a single break in the last possible "slice" which means that you get the break and the finish timer at around the same time.

**Comment by jenspfahl** [comment]
Actually I won't do that. The breaks are the core concept of the app. Otherwise any other timer would serve the same purpose.

**Comment by Quantum-Future** [comment]
I understand that the breaks are the core concept and the main usage scenario, but allowing zero breaks would enable using this app for both cases: as a break timer and conventional timer.

**Comment by jenspfahl** [comment]
Got it. It seems like a demanded feature, so I will make that happen.

**Comment by jenspfahl** [comment]
Added with v1.2.1

**Comment by Insti** [comment]
Awesome, Thanks :heart:
